<?php
$branchPages = [
    'mtdc-shah-alam' => [
        'name' => 'MTDC Shah Alam',
        'area' => 'Shah Alam',
        'headline' => 'Robotics, Coding & STEM Classes in MTDC Shah Alam',
        'address' => 'Universiti Teknologi MARA (UiTM) Shah Alam, UiTM-MTDC Technopreneur Centre, 40450 Shah Alam, Selangor.',
        'nearby' => 'UiTM Shah Alam, Seksyen 7, Seksyen 13, Glenmarie, Subang and Klang',
        'searchTerms' => 'robotics class Shah Alam, coding class Shah Alam, STEM class UiTM Shah Alam',
        'image' => 'TRIAL CLASS/6233119207726369610.jpg',
        'secondaryImage' => 'YOUNG CODER/6289668976233530628.jpg',
        'mapQuery' => 'UiTM-MTDC Technopreneur Centre Shah Alam',
    ],
    'bandar-puteri-bangi' => [
        'name' => 'Bandar Puteri Bangi',
        'area' => 'Bangi / Kajang',
        'headline' => 'Robotics, Coding & STEM Classes in Bandar Puteri Bangi',
        'address' => '22-1, Jln Puteri 2A/3, Bandar Bukit Mahkota, 43000 Kajang, Selangor.',
        'nearby' => 'Bangi, Kajang, Bandar Bukit Mahkota, Nilai and Semenyih',
        'searchTerms' => 'robotics class Bangi, coding class Bangi, coding class Kajang',
        'image' => 'LITTLE MAKER/6127599252902364638.jpg',
        'secondaryImage' => 'junior-maker/6292029357119180673.jpg',
        'mapQuery' => '22-1 Jalan Puteri 2A/3 Bandar Bukit Mahkota Kajang',
    ],
    'puncak-alam' => [
        'name' => 'Puncak Alam',
        'area' => 'Puncak Alam',
        'headline' => 'Robotics, Coding & STEM Classes in Puncak Alam',
        'address' => 'Pusat Perdagangan Hillpark, 2-1, Jln Hillpark 11/7, Bandar Hillpark, 42300 Puncak Alam, Selangor.',
        'nearby' => 'Puncak Alam, Bandar Hillpark, Alam Jaya, Kuala Selangor and Meru',
        'searchTerms' => 'robotics class Puncak Alam, coding class Puncak Alam, STEM class Bandar Hillpark',
        'image' => 'TRIAL CLASS/6213062741246200287.jpg',
        'secondaryImage' => 'LITTLE MAKER/6274016526272760775.jpg',
        'mapQuery' => '2-1 Jalan Hillpark 11/7 Bandar Hillpark Puncak Alam',
    ],
    'seksyen-7-shah-alam' => [
        'name' => 'Seksyen 7 Shah Alam',
        'area' => 'Shah Alam',
        'headline' => 'Robotics, Coding & STEM Classes in Seksyen 7 Shah Alam',
        'address' => '27B, Jalan Plumbum P 7/P, Seksyen 7, 40000 Shah Alam, Selangor.',
        'nearby' => 'Seksyen 7, UiTM Shah Alam, i-City, Padang Jawa and Klang',
        'searchTerms' => 'robotics class Seksyen 7 Shah Alam, coding class Seksyen 7, STEM class Shah Alam',
        'image' => 'YOUNG CODER/6332290036950747253.jpg',
        'secondaryImage' => 'YOUNG CODER/6289562924901057920.jpg',
        'mapQuery' => '27B Jalan Plumbum P 7/P Seksyen 7 Shah Alam',
    ],
    'seksyen-13-shah-alam' => [
        'name' => 'Seksyen 13 Shah Alam',
        'area' => 'Shah Alam',
        'headline' => 'Robotics, Coding & STEM Classes in Seksyen 13 Shah Alam',
        'address' => '1-07, Metia Residence, 5, Persiaran Sukan, Seksyen 13, 40100 Shah Alam, Selangor.',
        'nearby' => 'Seksyen 13, Stadium Shah Alam, Glenmarie, Subang and Kota Kemuning',
        'searchTerms' => 'robotics class Seksyen 13 Shah Alam, coding class Seksyen 13, STEM class Shah Alam',
        'image' => 'junior-maker/6332120956976958538.jpg',
        'secondaryImage' => 'YOUNG INNOVATOR/6224231966908204835.jpg',
        'mapQuery' => 'Metia Residence Persiaran Sukan Seksyen 13 Shah Alam',
    ],
    'cyberjaya' => [
        'name' => 'Cyberjaya',
        'area' => 'Cyberjaya',
        'headline' => 'Robotics, Coding & STEM Classes in Cyberjaya',
        'address' => '4807-1-17, 2, Persiaran Flora, Cyberjaya, 63000 Cyberjaya, Selangor.',
        'nearby' => 'Cyberjaya, Putrajaya, Dengkil, Puchong and Seri Kembangan',
        'searchTerms' => 'robotics class Cyberjaya, coding class Cyberjaya, STEM class Cyberjaya',
        'image' => 'YOUNG CODER/6289668976233530628.jpg',
        'secondaryImage' => 'YOUNG INNOVATOR/6332477108546291204.jpg',
        'mapQuery' => '4807-1-17 Persiaran Flora Cyberjaya',
    ],
    'bandar-baru-selayang' => [
        'name' => 'Bandar Baru Selayang',
        'area' => 'Selayang',
        'headline' => 'Robotics, Coding & STEM Classes in Bandar Baru Selayang',
        'address' => 'Unit SH-16-2, Selayang 18, Selayang, Selangor.',
        'nearby' => 'Selayang, Batu Caves, Gombak, Kepong and Rawang',
        'searchTerms' => 'robotics class Selayang, coding class Selayang, STEM class Batu Caves',
        'image' => 'TRIAL CLASS/6271273459509824648.jpg',
        'secondaryImage' => 'TRIAL CLASS/6068607649458538672.jpg',
        'mapQuery' => 'Selayang 18 Unit SH-16-2 Selayang',
    ],
];
?>
